[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "ffmpeg-python>=0.2.0",
    "jsonargparse>=4.40.0",
]
